[features]
seeds = false
[programs.devnet]
mugs_marketplace = "C29hER4SXQr3atHsuCrRmLAkXBpxvfLMCNeXg2TRTd9o"

[registry]
url = "https://anchor.projectserum.com"

[provider]
# cluster = "http://127.0.0.1:8899"
cluster = "localnet"
wallet = "/home/ubuntu/fury/deploy-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
